### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by nitedani** [cyco130/vavite#2]
Windows 11
Node 16.15.0
![image](https://user-images.githubusercontent.com/67418286/173229105-f9e578f0-3268-490b-9d7b-275f6ddcf945.png)

**Comment by cyco130** [comment]
Thanks for bringing this up!

Currently `vavite` doesn't support being installed globally. It expects to find a local `vite` installation (it's a peer dependency), that's why you're getting this error. I don't plan to support this use case yet but I'll try to improve the error message. Please install locally.

**Comment by cyco130** [comment]
Sorry, I haven't read it thoroughly :)

It looks like something else, I'll have a look at the first opportunity. Reopening.

**Comment by cyco130** [comment]
It should be fixed on 1.3.3. Thanks for reporting.

**Comment by fenos** [comment]
@cyco130 I'm getting the same error on v1.4.1
